[colors.primary]
background = '#111318'
foreground = '#e2e2e9'

[colors.selection]
text = '#e2e2e9'
background = '#294677'

[colors.cursor]
text = '#111318'
cursor = '#abc7ff'

[colors.normal]
black   = '#111318'
red     = '#ff729a'
green   = '#7fff92'
yellow  = '#fff872'
blue    = '#92b2f2'
magenta = '#2e4676'
cyan    = '#abc7ff'
white   = '#eff4ff'

[colors.bright]
black   = '#999da5'
red     = '#ff9fba'
green   = '#a5ffb3'
yellow  = '#fffaa5'
blue    = '#b7cfff'
magenta = '#c4d7ff'
cyan    = '#d9e5ff'
white   = '#f8faff'
