return {
  "nvim-lua/plenary.nvim",
  "MunifTanjim/nui.nvim",
  { "rmagatti/auto-session", config = { auto_session_use_git_branch = true } },
  "samjwill/nvim-unception",
  "tpope/vim-dadbod",
  "kristijanhusak/vim-dadbod-ui",
  "kristijanhusak/vim-dadbod-completion",
  "github/copilot.vim",
  "cseickel/diagnostic-window.nvim",
  { "rrethy/vim-hexokinase", build = "make hexokinase" },
  "itchyny/vim-gitbranch",
  "antoinemadec/FixCursorHold.nvim",
  "tpope/vim-repeat",
  "tpope/vim-eunuch",
  "tpope/vim-surround",
  "tpope/vim-fugitive",
  "junegunn/vim-easy-align",
  "wellle/targets.vim",
  "dkarter/bullets.vim",
  "nvim-treesitter/nvim-treesitter-textobjects",
  "svermeulen/vim-cutlass",
  "nvim-pack/nvim-spectre",
  "famiu/bufdelete.nvim",
  { "edluffy/hologram.nvim", config = {  auto_display = true } },
  { 'edluffy/hologram.nvim', config = { auto_display = true } },
  --{ "nvim-tree/nvim-tree.lua", setup = true },
}
