return {
  "nvim-treesitter/playground",
  "nvim-lua/plenary.nvim",
  "MunifTanjim/nui.nvim",
  { "rmagatti/auto-session", config = { auto_session_use_git_branch = true } },
  "cseickel/diagnostic-window.nvim",
  "itchyny/vim-gitbranch",
  "tpope/vim-fugitive",
  "tpope/vim-repeat",
  "tpope/vim-eunuch",
  "tpope/vim-surround",
  "junegunn/vim-easy-align",
  --"vim-table-mode",
  "wellle/targets.vim",
  --"nvim-treesitter/nvim-treesitter-textobjects",
  "svermeulen/vim-cutlass",
  --"nvim-pack/nvim-spectre",
  "famiu/bufdelete.nvim",
  "yioneko/nvim-vtsls",
  --{ "nvim-tree/nvim-tree.lua", setup = true },
}
