cursor #e2e2e9
cursor_text_color #c4c6d0

foreground            #e2e2e9
background            #111318
selection_foreground  #283041
selection_background  #bec6dc
url_color             #abc7ff

color0   #111318
color1   #ff729a
color2   #7fff92
color3   #fff872
color4   #92b2f2
color5   #2e4676
color6   #abc7ff
color7   #eff4ff
color8   #999da5
color9   #ff9fba
color10  #a5ffb3
color11  #fffaa5
color12  #b7cfff
color13  #c4d7ff
color14  #d9e5ff
color15  #f8faff
